Repository platformplatform/PlatformPlatform, pull requests merged in 2024-02, with the labels that each got.

#307 Fix Npm Audit
  application/account-management/WebApp/.storybook/main.ts
  application/account-management/WebApp/.storybook/preview.ts
  application/account-management/WebApp/.storybook/rspack.config.ts
  application/account-management/WebApp/package.json
  application/account-management/WebApp/stories/AlertDialog.stories.tsx
  application/account-management/WebApp/stories/Breadcrumbs.stories.tsx
  application/account-management/WebApp/stories/Calendar.stories.tsx
  application/account-management/WebApp/stories/ComboBox.stories.tsx
  application/account-management/WebApp/stories/DateField.stories.tsx
  application/account-management/WebApp/stories/DatePicker.stories.tsx
  application/account-management/WebApp/stories/DateRangePicker.stories.tsx
  application/account-management/WebApp/stories/Form.stories.tsx
  application/account-management/WebApp/stories/GridList.stories.tsx
  application/account-management/WebApp/stories/Link.stories.tsx
  application/account-management/WebApp/stories/ListBox.stories.tsx
  application/account-management/WebApp/stories/Menu.stories.tsx
  application/account-management/WebApp/stories/Meta.ts
  application/account-management/WebApp/stories/Meter.stories.tsx
  application/account-management/WebApp/stories/NumberField.stories.tsx
  application/account-management/WebApp/stories/Popover.stories.tsx
  application/account-management/WebApp/stories/ProgressBar.stories.tsx
  application/account-management/WebApp/stories/RangeCalendar.stories.tsx
  application/account-management/WebApp/stories/SearchField.stories.tsx
  application/account-management/WebApp/stories/Select.stories.tsx
  application/account-management/WebApp/stories/Slider.stories.tsx
  application/account-management/WebApp/stories/Switch.stories.tsx
  application/account-management/WebApp/stories/Table.stories.tsx
  application/account-management/WebApp/stories/Tabs.stories.tsx
  application/account-management/WebApp/stories/TagGroup.stories.tsx
  application/account-management/WebApp/stories/TextField.stories.tsx
  application/account-management/WebApp/stories/TimeField.stories.tsx
  application/account-management/WebApp/stories/ToggleButton.stories.tsx
  application/account-management/WebApp/stories/Toolbar.stories.tsx
  application/account-management/WebApp/stories/Tooltip.stories.tsx
  application/yarn.lock
Labels: enhancement

#308 Remove HtmlRspackPlugin dependencies
  application/account-management/WebApp/package.json
  application/account-management/WebApp/rspack.config.ts
  application/yarn.lock
Labels: enhancement

#309 Update .NET ecosystem and NuGet packages to latest versions including .NET Aspire Preview 3
  application/AppHost/Program.cs
  application/Directory.Packages.props
  application/dotnet-tools.json
  application/global.json
  developer-cli/Installation/PrerequisitesChecker.cs
Labels: enhancement

#310 Upgrade GitHub actions to latest versions for Node.js compatibility
  .github/workflows/_publish-container.yml
  .github/workflows/application.yml
  .github/workflows/cloud-infrastructure.yml
Labels: enhancement

#312 Update README with new intro and clear steps for getting started
  README.md
Labels: enhancement

#313 Minor update to README intro to make it more readable
  README.md
Labels: enhancement

#317 Fix broken link for the mono repository section
  README.md
Labels: documentation

#318 Specify a specific port for the SQL server container
  application/AppHost/Program.cs
Labels: enhancement

#331 Add robots.txt and copy of public folder
  application/account-management/WebApp/public/favicon.ico
  application/account-management/WebApp/public/index.html
  application/account-management/WebApp/public/robots.txt
  application/account-management/WebApp/rspack.config.ts
Labels: enhancement

#330 WebApp image support
  application/account-management/WebApp/rspack.config.ts
Labels: enhancement

#332 WebApp add more CSP and security headers
  application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
Labels: enhancement

#334 Add middleware security headers
  application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
  application/shared-kernel/ApiCore/Middleware/SecurityHeaderMiddleware.cs
Labels: enhancement

#338 Refactor WebAppMiddleware into IMiddleware
  application/account-management/Api/Program.cs
  application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
Labels: enhancement

#339 Improve the webapp routes generation
  application/account-management/WebApp/app/not-found.tsx
  application/account-management/WebApp/app/tenant/create/actions.ts
  application/account-management/WebApp/lib/router/router.ts
  application/account-management/WebApp/main.tsx
  application/account-management/WebApp/package.json
  application/account-management/WebApp/rspack.config.ts
  application/client-foundation/clientFilesystemRouter/lib/ClientFilesystemRouter.ts
  application/client-foundation/clientFilesystemRouter/lib/generateReactRouter.ts
  application/client-foundation/clientFilesystemRouter/lib/pageReactRoutesCode.ts
  application/client-foundation/clientFilesystemRouter/react/ReactFilesystemRouter
  application/client-foundation/clientFilesystemRouter/react/ReactFilesystemRouter.d.ts
  application/client-foundation/clientFilesystemRouter/rspack-plugin.ts
Labels: enhancement

#341 Add permission policy header
  application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
  application/shared-kernel/ApiCore/Middleware/SecurityHeaderMiddleware.cs
  application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
Labels: enhancement

#342 Create Azure Communication and Email Communication Service resources
  README.md
  cloud-infrastructure/cluster/main-cluster.bicep
  cloud-infrastructure/modules/communication-services.bicep
  cloud-infrastructure/modules/container-app.bicep
  cloud-infrastructure/modules/key-vault.bicep
Labels: enhancement

#345 Fix the execution of azure cli commands for windows
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Labels: bug

#343 WebApp Add initial UserInfo
  application/account-management/WebApp/global.d.ts
  application/account-management/WebApp/rspack.config.ts
  application/account-management/WebApp/shared/rspack/runtime.ts
  application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
Labels: enhancement

#347 Fix dependencies between Azure Container App and Communication Services
  cloud-infrastructure/cluster/deploy-cluster.sh
  cloud-infrastructure/cluster/main-cluster.bicep
Labels: bug

#348 Create email signature service for both production and development
  application/AppHost/Program.cs
  application/Directory.Packages.props
  application/shared-kernel/ApplicationCore/Services/IEmailService.cs
  application/shared-kernel/InfrastructureCore/InfrastructureCore.csproj
  application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
  application/shared-kernel/InfrastructureCore/Services/AzureEmailService.cs
  application/shared-kernel/InfrastructureCore/Services/DevelopmentEmailService.cs
Labels: enhancement

#349 Fix failing Entity Framework migrations
  application/account-management/Api/appsettings.json
  application/account-management/Directory.Build.props
  application/shared-kernel/Directory.Build.props
Labels: enhancement

#352 Set up API endpoints for completing account registration flow
  application/account-management/Api/AccountRegistrations/AccountRegistrationsEndpoints.cs
  application/account-management/Api/Program.cs
  application/account-management/Application/AccountRegistrations/ConfirmAccountRegistrationEmail.cs
  application/account-management/Application/AccountRegistrations/StartAccountRegistration.cs
  application/account-management/Application/TelemetryEvents/TelemetryEvents.cs
  application/account-management/Application/Tenants/CreateTenant.cs
  application/account-management/Application/Tenants/TenantCreatedEventHandler.cs
  application/account-management/Application/Tenants/TenantResponseDto.cs
  application/account-management/Application/Tenants/TenantValidator.cs
  application/account-management/Application/Tenants/UpdateTenant.cs
  application/account-management/Application/Users/CreateUser.cs
  application/account-management/Application/Users/UserResponseDto.cs
  application/account-management/Domain/AccountRegistrations/AccountRegistration.cs
  application/account-management/Domain/AccountRegistrations/IAccountRegistrationRepository.cs
  application/account-management/Domain/Tenants/Tenant.cs
  application/account-management/Domain/Tenants/TenantEvents.cs
  application/account-management/Domain/Users/User.cs
  application/account-management/Infrastructure/AccountManagementDbContext.cs
  application/account-management/Infrastructure/AccountRegistrations/AccountRegistrationRepository.cs
  application/account-management/Infrastructure/Migrations/20230618152042_Initial.Designer.cs
  application/account-management/Infrastructure/Migrations/20230618152042_Initial.cs
  application/account-management/Infrastructure/Migrations/20240221234207_AddAccountRegistrations.Designer.cs
  application/account-management/Infrastructure/Migrations/20240221234207_AddAccountRegistrations.cs
  application/account-management/Infrastructure/Migrations/AccountManagementDbContextModelSnapshot.cs
  application/account-management/Tests/Api/Tenants/TenantEndpointsTests.cs
  application/account-management/Tests/Api/Users/UserEndpointsTests.cs
  application/account-management/Tests/Application/Tenants/CreateTenantValidationTests.cs
  application/account-management/Tests/Application/Tenants/TenantCreatedEventHandlerTests.cs
  application/account-management/Tests/DatabaseSeeder.cs
  application/account-management/Tests/FakerExtensions.cs
  application/account-management/WebApp/app/tenant/create/actions.ts
  application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
  application/shared-kernel/ApplicationCore/Behaviors/PublishTelemetryEventsPipelineBehavior.cs
  application/shared-kernel/ApplicationCore/Behaviors/UnitOfWorkPipelineBehavior.cs
  application/shared-kernel/ApplicationCore/Behaviors/ValidationPipelineBehavior.cs
  application/shared-kernel/ApplicationCore/Cqrs/Result.cs
  application/shared-kernel/ApplicationCore/Services/IEmailService.cs
  application/shared-kernel/ApplicationCore/Validation/SharedValidations.cs
  application/shared-kernel/DomainCore/Entities/AudibleEntity.cs
  application/shared-kernel/DomainCore/Entities/IAuditableEntity.cs
  application/shared-kernel/InfrastructureCore/EntityFramework/ModelBuilderExtensions.cs
Labels: enhancement

#351 Set up basic react auth infrastructure
  application/account-management/WebApp/lib/auth/AccessDenied.tsx
  application/account-management/WebApp/lib/auth/AuthenticationProvider.tsx
  application/account-management/WebApp/lib/auth/SignedIn.tsx
  application/account-management/WebApp/lib/auth/SignedOut.tsx
  application/account-management/WebApp/lib/auth/actions.ts
  application/account-management/WebApp/lib/auth/hooks.ts
  application/account-management/WebApp/lib/auth/mock.api.ts
  application/account-management/WebApp/translations/locale/da-DK.po
  application/account-management/WebApp/translations/locale/en-US.po
  application/account-management/WebApp/translations/locale/pseudo.po
Labels: enhancement

#353 Fix typo when calling an Azure CLI command
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Labels: bug

#355 WebApp add initial signin page
  application/account-management/WebApp/app/login/layout.tsx
  application/account-management/WebApp/app/login/page.tsx
  application/account-management/WebApp/app/page.tsx
  application/account-management/WebApp/translations/locale/da-DK.po
  application/account-management/WebApp/translations/locale/en-US.po
  application/account-management/WebApp/translations/locale/pseudo.po
  application/account-management/WebApp/ui/Auth/LoginForm.tsx
  application/account-management/WebApp/ui/Auth/logo-mark.png
  application/account-management/WebApp/ui/Auth/powered-by.png
  application/account-management/WebApp/ui/components/Button.tsx
  application/account-management/WebApp/ui/components/Field.tsx
Labels: enhancement

#358 WebApp add initial sign up and verification flow
  application/account-management/WebApp/app/register/[registrationId]/error.tsx
  application/account-management/WebApp/app/register/[registrationId]/page.tsx
  application/account-management/WebApp/app/register/layout.tsx
  application/account-management/WebApp/app/register/page.tsx
  application/account-management/WebApp/lib/router/router.ts
  application/account-management/WebApp/translations/locale/da-DK.po
  application/account-management/WebApp/translations/locale/en-US.po
  application/account-management/WebApp/translations/locale/pseudo.po
  application/account-management/WebApp/ui/Auth/SignUpForm.tsx
  application/account-management/WebApp/ui/Auth/SignUpVerifyForm.tsx
  application/account-management/WebApp/ui/Auth/actions.ts
  application/account-management/WebApp/ui/Auth/otp/Digit.tsx
  application/account-management/WebApp/ui/Auth/otp/DigitPattern.tsx
  application/account-management/WebApp/ui/Auth/otp/OneTimeCodeInput.tsx
  application/account-management/WebApp/ui/Auth/otp/VerificationExpirationError.ts
  application/account-management/WebApp/ui/Auth/otp/useExpiration.ts
  application/client-foundation/clientFilesystemRouter/lib/pageReactRoutesCode.ts
Labels: enhancement
