Repository platformplatform/PlatformPlatform, pull requests merged in 2024-04, with the labels that each got.

#400 Publish containers using .NET instead of Docker and build trimmed and chiseled images
  .github/workflows/_publish-container.yml
  .github/workflows/application.yml
  application/account-management/Api/Api.csproj
  application/account-management/Api/Dockerfile
  application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
Labels: enhancement

#405 Add blob storage infrastructure to Account Management and create avatars container
  cloud-infrastructure/cluster/main-cluster.bicep
  cloud-infrastructure/modules/container-app.bicep
  cloud-infrastructure/modules/microsoft-sql-server-diagnostic.bicep
  cloud-infrastructure/modules/role-assignments-container-registry-acr-pull.bicep
  cloud-infrastructure/modules/role-assignments-storage-blob-data-contributor.bicep
  cloud-infrastructure/modules/storage-account.bicep
Labels: enhancement

#407 Create Container App for AppGateway and configure initial container on first infrastructure deployment
  cloud-infrastructure/cluster/deploy-cluster.sh
  cloud-infrastructure/cluster/main-cluster.bicep
  cloud-infrastructure/modules/communication-services.bicep
  cloud-infrastructure/modules/container-app.bicep
  cloud-infrastructure/modules/container-apps-environment.bicep
  cloud-infrastructure/modules/microsoft-sql-database.bicep
  cloud-infrastructure/modules/resource-group-lock.bicep
  cloud-infrastructure/modules/role-assignments-storage-blob-data-reader.bicep
  cloud-infrastructure/modules/storage-account.bicep
Labels: enhancement

#410 Fix different errors when setting up custom domain
  cloud-infrastructure/cluster/deploy-cluster.sh
  cloud-infrastructure/modules/container-app.bicep
Labels: enhancement

#412 Configure deployment for App Gateway and standardize naming of GitHub action steps
  .github/workflows/application.yml
  application/AppGateway/AppGateway.csproj
Labels: enhancement

#413 Change API container image to use jammy-chiseled-extra container image which includes ICU libraries
  application/account-management/Api/Api.csproj
Labels: bug

#415 Upgrade .NET NuGet packages and .NET tooling
  application/Directory.Packages.props
  application/dotnet-tools.json
Labels: enhancement

#414 Introduce user avatars with Gravatar fallback and YARP for public sharing of private blobs
  application/AppGateway/AppGateway.csproj
  application/AppGateway/ClusterDestinationConfigFilter.cs
  application/AppGateway/ManagedIdentityTransform.cs
  application/AppGateway/Program.cs
  application/AppGateway/SharedAccessSignatureRequestTransform.cs
  application/AppGateway/appsettings.json
  application/AppHost/AppHost.csproj
  application/AppHost/Program.cs
  application/AppHost/appsettings.Development.json
  application/AppHost/appsettings.json
  application/Directory.Packages.props
  application/account-management/Api/Api.csproj
  application/account-management/Api/Program.cs
  application/account-management/Api/Users/UserEndpoints.cs
  application/account-management/Api/appsettings.development.json
  application/account-management/Application/TelemetryEvents/TelemetryEvents.cs
  application/account-management/Application/Users/CreateUser.cs
  application/account-management/Application/Users/GetUsers.cs
  application/account-management/Application/Users/GetUsersDto.cs
  application/account-management/Application/Users/GetUsersResponseDto.cs
  application/account-management/Application/Users/RemoveAvatar.cs
  application/account-management/Application/Users/UpdateAvatar.cs
  application/account-management/Application/Users/UserResponseDto.cs
  application/account-management/Domain/Users/User.cs
  application/account-management/Infrastructure/AccountManagementDbContext.cs
  application/account-management/Infrastructure/InfrastructureConfiguration.cs
  application/account-management/Infrastructure/Migrations/20240307000000_Initial.Designer.cs
  application/account-management/Infrastructure/Migrations/20240307000000_Initial.cs
  application/account-management/Infrastructure/Migrations/AccountManagementDbContextModelSnapshot.cs
  application/account-management/Tests/Api/Users/UserEndpointsTests.cs
  application/account-management/Tests/DatabaseSeeder.cs
  application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
  application/shared-kernel/ApplicationCore/Services/IBlobStorage.cs
  application/shared-kernel/InfrastructureCore/InfrastructureCore.csproj
  application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
  application/shared-kernel/InfrastructureCore/Services/BlobStorage.cs
Labels: enhancement

#416 Ensure uploaded avatars are persisted between Aspire sessions
  application/AppHost/Program.cs
Labels: bug

#417 Reintroduce Dockerfile for building containers to get smaller and safer images
  .github/workflows/_publish-container.yml
  .github/workflows/application.yml
  application/AppGateway/AppGateway.csproj
  application/AppGateway/Dockerfile
  application/account-management/Api/Api.csproj
  application/account-management/Api/Dockerfile
Labels: bug, enhancement

#421 Update strongly typed IDs to have a human-readable prefix
  application/account-management/Domain/AccountRegistrations/AccountRegistration.cs
  application/account-management/Domain/Users/UserTypes.cs
  application/account-management/Infrastructure/Migrations/20240307000000_Initial.Designer.cs
  application/account-management/Infrastructure/Migrations/20240307000000_Initial.cs
  application/account-management/Infrastructure/Migrations/AccountManagementDbContextModelSnapshot.cs
  application/account-management/Tests/Api/Users/UserEndpointsTests.cs
  application/account-management/Tests/ArchitectureTests/IdPrefixForAllStronglyTypedUlidTests.cs
  application/account-management/Tests/ArchitectureTests/PublicClassesTests.cs
  application/account-management/Tests/FakerExtensions.cs
  application/shared-kernel/DomainCore/Identity/IdPrefixAttribute.cs
  application/shared-kernel/DomainCore/Identity/StronglyTypedUlid.cs
  application/shared-kernel/Tests/DomainCore/Identity/StronglyTypedUlidTests.cs
Labels: enhancement

#422 Update to .NET Aspire preview 5
  application/AppHost/AppHost.csproj
  application/AppHost/Program.cs
  application/AppHost/Properties/launchSettings.json
  application/AppHost/SecretManagerHelper.cs
  application/Directory.Packages.props
  application/shared-kernel/ApiCore/Aspire/ServiceDefaultsExtensions.cs
  developer-cli/Commands/ConfigureDeveloperEnvironmentCommand.cs
  developer-cli/Commands/InstallCommand.cs
  developer-cli/Commands/RunCommand.cs
  developer-cli/Commands/UninstallCommand.cs
  developer-cli/Installation/PrerequisitesChecker.cs
Labels: enhancement

#426 Remove deprecated package Microsoft.AspNetCore.Mvc.ApiExplorer
  application/shared-kernel/ApiCore/ApiCore.csproj
Labels: enhancement

#429 Add support for development on Linux and Windows WSL
  .gitignore
  README.md
  developer-cli/Commands/ConfigureDeveloperEnvironmentCommand.cs
  developer-cli/Commands/InstallCommand.cs
  developer-cli/Commands/UninstallCommand.cs
  developer-cli/Installation/Configuration.cs
  developer-cli/Installation/PrerequisitesChecker.cs
  developer-cli/Program.cs
Labels: enhancement

#430 Create SSL certificate when running AppHost, eliminating need for installing CLI when getting started
  README.md
  application/AppHost/Program.cs
  application/AppHost/SslCertificateManager.cs
  application/account-management/WebApp/rspack.config.ts
  developer-cli/Commands/ConfigureDeveloperEnvironmentCommand.cs
  developer-cli/Commands/InstallCommand.cs
  developer-cli/Commands/RunCommand.cs
  developer-cli/Commands/UninstallCommand.cs
  developer-cli/Installation/Configuration.cs
  developer-cli/Installation/PrerequisitesChecker.cs
Labels: enhancement

#431 Enable development of Account Management self-contained systems in isolation
  application/account-management/AccountManagement.sln
Labels: enhancement

#433 Update README.md
  README.md
Labels: enhancement

#434 Update to .NET Aspire preview 6
  application/Directory.Packages.props
  application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
  application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareConfiguration.cs
  developer-cli/Installation/PrerequisitesChecker.cs
Labels: enhancement

#435 Add tests for user search endpoint
  application/account-management/Application/Users/UpdateUser.cs
  application/account-management/Domain/Users/User.cs
  application/account-management/Infrastructure/Users/UserRepository.cs
  application/account-management/Tests/Api/BaseApiTest.cs
  application/account-management/Tests/Api/Tenants/TenantEndpointsTests.cs
  application/account-management/Tests/Api/Users/UserEndpointsTests.cs
  application/account-management/Tests/DatabaseSeeder.cs
Labels: enhancement

#436 Optimize frontend startup time when using Aspire
  .github/workflows/application.yml
  application/account-management/Api/Properties/launchSettings.json
  application/account-management/Tests/Api/BaseApiTest.cs
  application/account-management/WebApp/WebApp.esproj
  application/account-management/WebApp/package.json
  application/account-management/WebApp/rspack.config.ts
Labels: enhancement

#437 Speed up starting and simplify building the WebApp
  .github/workflows/application.yml
  application/AppGateway/AppGateway.csproj
  application/account-management/Api/Api.csproj
  application/account-management/WebApp/App.tsx
  application/account-management/WebApp/WebApp.esproj
  application/account-management/WebApp/dist/index.html
  application/account-management/WebApp/package.json
  application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareConfiguration.cs
  application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareExtensions.cs
Labels: enhancement

#439 Correct directory name for developer cli
  README.md
Labels: enhancement
