Repository platformplatform/PlatformPlatform, pull requests merged in 2024-06, with the labels that each got.

#478 Add User Management page with dummy data and Admin Center skeleton
  .vscode/settings.json
  application/account-management/WebApp/app/_landing/sections/CommunitySection.tsx
  application/account-management/WebApp/app/_landing/sections/FeatureSection.tsx
  application/account-management/WebApp/app/_landing/sections/HeroSection.tsx
  application/account-management/WebApp/app/admin/images/avatar.png
  application/account-management/WebApp/app/admin/page.tsx
  application/account-management/WebApp/app/admin/users/UserHeader.tsx
  application/account-management/WebApp/app/admin/users/UserInvite.tsx
  application/account-management/WebApp/app/admin/users/UserQuerying.tsx
  application/account-management/WebApp/app/admin/users/UserTable.tsx
  application/account-management/WebApp/app/admin/users/UserTabs.tsx
  application/account-management/WebApp/app/admin/users/data.tsx
  application/account-management/WebApp/app/admin/users/page.tsx
  application/account-management/WebApp/app/dashboard/loading.tsx
  application/account-management/WebApp/app/layout.tsx
  application/account-management/WebApp/app/login/components/LoginForm.tsx
  application/account-management/WebApp/app/register/components/actions.ts
  application/account-management/WebApp/dist/index.html
  application/account-management/WebApp/main.css
  application/account-management/WebApp/package.json
  application/account-management/WebApp/public/index.html
  application/account-management/WebApp/ui/components/Badge.tsx
  application/account-management/WebApp/ui/components/Pagination.tsx
  application/account-management/WebApp/ui/components/SideMenu.tsx
  application/account-management/WebApp/ui/components/Table.tsx
  application/account-management/WebApp/ui/components/Tabs.tsx
  application/yarn.lock
Labels: enhancement

#483 Hardcode theme mode to light mode
  application/account-management/WebApp/dist/index.html
  application/account-management/WebApp/public/index.html
Labels: enhancement

#484 Revert and optimize database migration and email handling processes
  application/account-management/Workers/Program.cs
  application/back-office/Workers/Program.cs
  application/shared-kernel/InfrastructureCore/InfrastructureCoreConfiguration.cs
  application/shared-kernel/InfrastructureCore/Services/AzureEmailService.cs
Labels: bug

#488 Simplify SinglePageApp and static file serving with .NET Minimal API MapFallback
  .gitignore
  application/account-management/Api/Program.cs
  application/account-management/Tests/Api/BaseApiTest.cs
  application/account-management/WebApp/dist/index.html
  application/back-office/Api/Program.cs
  application/back-office/Tests/Api/BaseApiTest.cs
  application/back-office/WebApp/dist/index.html
  application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
  application/shared-kernel/ApiCore/Middleware/WebAppMiddleware.cs
  application/shared-kernel/ApiCore/Middleware/WebAppMiddlewareExtensions.cs
  application/shared-kernel/ApiCore/SinglePageApp/SinglePageAppConfiguration.cs
  application/shared-kernel/ApiCore/SinglePageApp/SinglePageAppFallbackExtensions.cs
  application/shared-kernel/ApiCore/SinglePageApp/UserInfo.cs
Labels: enhancement

#494 Fix failed publishing of frontend artifacts
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
  .github/workflows/back-office.yml
  application/account-management/WebApp/pages/-landing/sections/TechnologySection2.tsx
  application/account-management/WebApp/pages/__root.tsx
  application/account-management/WebApp/pages/login/_layout.tsx
  application/account-management/WebApp/public/index.html
  application/account-management/WebApp/shared/lib/applicationInsights/ApplicationInsightsProvider.tsx
  application/account-management/WebApp/shared/lib/auth/AuthenticationProvider.tsx
  application/account-management/WebApp/shared/lib/router/ReactAriaRouterProvider.tsx
  application/account-management/WebApp/shared/ui/DomainInput.tsx
  application/account-management/WebApp/shared/ui/LocaleSwitcher.tsx
  application/back-office/WebApp/pages/__root.tsx
  application/back-office/WebApp/public/index.html
  application/back-office/WebApp/shared/lib/applicationInsights/ApplicationInsightsProvider.tsx
  application/back-office/WebApp/shared/lib/auth/AuthenticationProvider.tsx
  application/back-office/WebApp/shared/lib/router/ReactAriaRouterProvider.tsx
Labels: bug

#495 Update Developer CLI for improved flexibility and consistency
  developer-cli/Commands/BuildCommand.cs
  developer-cli/Commands/CodeCleanupCommand.cs
  developer-cli/Commands/CodeCoverageCommand.cs
  developer-cli/Commands/CodeInspectionsCommand.cs
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
  developer-cli/Commands/DevCommand.cs
  developer-cli/Commands/InstallCommand.cs
  developer-cli/Commands/TestCommand.cs
  developer-cli/Commands/TranslateCommand.cs
  developer-cli/Commands/UninstallCommand.cs
  developer-cli/Installation/ChangeDetection.cs
  developer-cli/Installation/Configuration.cs
  developer-cli/Installation/PrerequisitesChecker.cs
  developer-cli/Utilities/DockerServer.cs
  developer-cli/Utilities/GithubHelper.cs
  developer-cli/Utilities/ProcessHelper.cs
  developer-cli/Utilities/SolutionHelper.cs
Labels: enhancement

#496 Update formatting rules to align Visual Studio and code cleanup
  application/.editorconfig
  application/AppGateway/AppGateway.csproj
  application/AppHost/AppHost.csproj
  application/account-management/Api/AccountManagement.Api.csproj
  application/account-management/Application/AccountManagement.Application.csproj
  application/account-management/Directory.Build.props
  application/account-management/Domain/AccountManagement.Domain.csproj
  application/account-management/Infrastructure/AccountManagement.Infrastructure.csproj
  application/account-management/Tests/AccountManagement.Tests.csproj
  application/account-management/Workers/AccountManagement.Workers.csproj
  application/back-office/Api/BackOffice.Api.csproj
  application/back-office/Application/BackOffice.Application.csproj
  application/back-office/Directory.Build.props
  application/back-office/Domain/BackOffice.Domain.csproj
  application/back-office/Infrastructure/BackOffice.Infrastructure.csproj
  application/back-office/Tests/BackOffice.Tests.csproj
  application/back-office/Workers/BackOffice.Workers.csproj
  application/shared-kernel/ApiCore/Endpoints/TestEndpoints.cs
  application/shared-kernel/ApiCore/Middleware/GlobalExceptionHandler.cs
  application/shared-kernel/ApiCore/SharedKernel.ApiCore.csproj
  application/shared-kernel/ApplicationCore/SharedKernel.ApplicationCore.csproj
  application/shared-kernel/Directory.Build.props
  application/shared-kernel/DomainCore/SharedKernel.DomainCore.csproj
  application/shared-kernel/InfrastructureCore/SharedKernel.InfrastructureCore.csproj
  application/shared-kernel/Tests/SharedKernel.Tests.csproj
  developer-cli/.editorconfig
  developer-cli/DeveloperCli.csproj
  developer-cli/dotnet-tools.json
Labels: enhancement

#497 Update Bicep modules and ensure infrastructure deployment triggers
  .github/workflows/cloud-infrastructure.yml
  cloud-infrastructure/modules/container-app.bicep
  cloud-infrastructure/modules/key-vault.bicep
Labels: enhancement

#499 Remove links to API from the Aspire dashboard
  application/account-management/Api/Program.cs
  application/account-management/Api/Properties/launchSettings.json
  application/back-office/Api/Program.cs
  application/back-office/Api/Properties/launchSettings.json
  application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
Labels: enhancement

#498 Simplify code and improve TenantID and UserRole handling
  application/account-management/Application/AccountRegistrations/StartAccountRegistration.cs
  application/account-management/Application/Tenants/TenantCreatedEventHandler.cs
  application/account-management/Application/Users/CreateUser.cs
  application/account-management/Application/Users/UpdateUser.cs
  application/account-management/Application/Users/UserResponseDto.cs
  application/account-management/Application/Users/UserValidator.cs
  application/account-management/Domain/Tenants/TenantTypes.cs
  application/account-management/Domain/Users/User.cs
  application/account-management/Domain/Users/UserTypes.cs
  application/account-management/Infrastructure/Migrations/DatabaseMigrations.cs
  application/account-management/Infrastructure/Users/UserRepository.cs
  application/account-management/Tests/Api/AccountRegistrations/AccountRegistrationsTests.cs
  application/account-management/Tests/Api/Users/UserEndpointsTests.cs
  application/account-management/Tests/Application/AccountRegistrations/AccountRegistrationTests.cs
  application/account-management/Tests/DatabaseSeeder.cs
  application/account-management/WebApp/pages/admin/users/-components/data.tsx
  application/account-management/WebApp/pages/register/-components/actions.ts
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
  application/shared-kernel/ApiCore/SinglePageApp/SinglePageAppConfiguration.cs
  application/shared-kernel/ApiCore/SinglePageApp/SinglePageAppFallbackExtensions.cs
  application/shared-kernel/ApplicationCore/ApplicationCoreConfiguration.cs
Labels: enhancement

#501 Create HTTP Strict-Transport-Security ResponseHeaderValueTransform in AppGateway
  application/AppGateway/Program.cs
  application/AppGateway/Transformations/HttpStrictTransportSecurityTransform.cs
  application/AppGateway/Transformations/ManagedIdentityTransform.cs
Labels: enhancement

#504 Ensure GitHub workflows trigger on changes to shared-webapp
  .github/workflows/account-management.yml
  .github/workflows/back-office.yml
Labels: documentation

#506 Use specific match pattern to ignore own dist folder
  application/shared-webapp/build/plugin/DevelopmentServerPlugin.ts
Labels: enhancement

#507 Add title property to user
  application/account-management/Application/Users/UserResponseDto.cs
  application/account-management/Directory.Build.props
  application/account-management/Domain/AccountRegistrations/AccountRegistration.cs
  application/account-management/Domain/Users/User.cs
  application/account-management/Infrastructure/Migrations/DatabaseMigrations.cs
  application/account-management/Infrastructure/Users/UserRepository.cs
  application/account-management/Tests/Api/Users/UserEndpointsTests.cs
  application/account-management/Tests/DatabaseSeeder.cs
  application/back-office/Directory.Build.props
  developer-cli/Commands/BuildCommand.cs
  developer-cli/Commands/CodeCleanupCommand.cs
  developer-cli/Commands/CodeCoverageCommand.cs
  developer-cli/Commands/CodeInspectionsCommand.cs
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
  developer-cli/Commands/DevCommand.cs
  developer-cli/Commands/InstallCommand.cs
  developer-cli/Commands/TestCommand.cs
  developer-cli/Commands/TranslateCommand.cs
  developer-cli/Commands/UninstallCommand.cs
Labels: enhancement

#509 Move out shared web app infrastructure code
  application/account-management/WebApp/lingui.config.ts
  application/account-management/WebApp/main.tsx
  application/account-management/WebApp/pages/__root.tsx
  application/account-management/WebApp/pages/login/-components/LoginForm.tsx
  application/account-management/WebApp/rsbuild.config.ts
  application/account-management/WebApp/shared/lib/applicationInsights/ApplicationInsightsProvider.tsx
  application/account-management/WebApp/shared/lib/applicationInsights/ErrorFallback.tsx
  application/account-management/WebApp/shared/lib/applicationInsights/config.tsx
  application/account-management/WebApp/shared/lib/auth/actions.ts
  application/account-management/WebApp/shared/lib/router/ReactAriaRouterProvider.tsx
  application/account-management/WebApp/shared/lib/router/router.tsx
  application/account-management/WebApp/shared/translations/i18n.config.json
  application/account-management/WebApp/shared/translations/i18n.ts
  application/account-management/WebApp/shared/translations/locale/da-DK.po
  application/account-management/WebApp/shared/translations/locale/en-US.po
  application/account-management/WebApp/shared/ui/LocaleSwitcher.tsx
  application/back-office/WebApp/lingui.config.ts
  application/back-office/WebApp/main.tsx
  application/back-office/WebApp/pages/__root.tsx
  application/back-office/WebApp/rsbuild.config.ts
  application/back-office/WebApp/shared/lib/applicationInsights/ApplicationInsightsProvider.tsx
  application/back-office/WebApp/shared/lib/applicationInsights/ErrorFallback.tsx
  application/back-office/WebApp/shared/lib/auth/AccessDenied.tsx
  application/back-office/WebApp/shared/lib/auth/AuthenticationProvider.tsx
  application/back-office/WebApp/shared/lib/auth/SignedIn.tsx
  application/back-office/WebApp/shared/lib/auth/SignedOut.tsx
  application/back-office/WebApp/shared/lib/auth/hooks.ts
  application/back-office/WebApp/shared/lib/auth/mock.api.ts
  application/back-office/WebApp/shared/lib/router/ReactAriaRouterProvider.tsx
  application/back-office/WebApp/shared/lib/router/router.tsx
  application/back-office/WebApp/shared/lib/utils.ts
  application/back-office/WebApp/shared/translations/i18n.config.json
  application/back-office/WebApp/shared/translations/i18n.ts
  application/back-office/WebApp/shared/translations/locale/da-DK.po
  application/back-office/WebApp/shared/translations/locale/en-US.po
  application/package-lock.json
  application/shared-webapp/build/environment.d.ts
  application/shared-webapp/build/plugin/RunTimeEnvironmentPlugin.ts
  application/shared-webapp/infrastructure/applicationInsights/ApplicationInsightsProvider.tsx
  application/shared-webapp/infrastructure/auth/AccessDenied.tsx
  application/shared-webapp/infrastructure/auth/AuthenticationProvider.tsx
  application/shared-webapp/infrastructure/auth/SignedIn.tsx
  application/shared-webapp/infrastructure/auth/SignedOut.tsx
  application/shared-webapp/infrastructure/auth/actions.ts
  application/shared-webapp/infrastructure/auth/hooks.ts
  application/shared-webapp/infrastructure/auth/mock.api.ts
  application/shared-webapp/infrastructure/package.json
  application/shared-webapp/infrastructure/react-env.d.ts
  application/shared-webapp/infrastructure/router/ReactAriaRouterProvider.tsx
  application/shared-webapp/infrastructure/translations/Translation.tsx
  application/shared-webapp/infrastructure/translations/TranslationContext.tsx
  application/shared-webapp/infrastructure/translations/createLinguiConfig.ts
  application/shared-webapp/infrastructure/translations/i18n.config.json
  application/shared-webapp/infrastructure/tsconfig.json
  application/shared-webapp/ui/cn.ts
Labels: enhancement

#511 Add infrastructure for the user to change the theme mode
  application/account-management/WebApp/pages/-landing/sections/HeroSection.tsx
  application/account-management/WebApp/pages/__root.tsx
  application/back-office/WebApp/pages/__root.tsx
  application/package-lock.json
  application/package.json
  application/shared-webapp/build/package.json
  application/shared-webapp/infrastructure/package.json
  application/shared-webapp/infrastructure/themeMode/ThemeModeSelector.tsx
  application/shared-webapp/infrastructure/themeMode/useThemeMode.tsx
  application/shared-webapp/ui/package.json
  application/shared-webapp/utils/package.json
  application/turbo.json
Labels: enhancement

#515 Update User Management styling to align with design
  application/account-management/WebApp/pages/admin/users/-components/UserHeader.tsx
  application/account-management/WebApp/pages/admin/users/-components/UserInvite.tsx
  application/account-management/WebApp/pages/admin/users/-components/UserQuerying.tsx
  application/account-management/WebApp/pages/admin/users/-components/UserTable.tsx
  application/account-management/WebApp/pages/admin/users/-components/UserTabs.tsx
  application/account-management/WebApp/pages/admin/users/-components/data.tsx
  application/account-management/WebApp/pages/admin/users/-components/profileMenuItem.tsx
  application/account-management/WebApp/pages/admin/users/index.tsx
Labels: enhancement

#516 Ensure .sln file format consistency with Visual Studio 2022
  application/PlatformPlatform.sln
Labels: enhancement

#518 Update API endpoint for updating user and create separate endpoint for changing user role
  application/account-management/Api/Users/UserEndpoints.cs
  application/account-management/Application/TelemetryEvents/TelemetryEvents.cs
  application/account-management/Application/Users/ChangeUserRole.cs
  application/account-management/Application/Users/UpdateUser.cs
  application/account-management/Tests/Api/Users/UserEndpointsTests.cs
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
Labels: enhancement

#519 Set up kestrel to listen to localhost instead of any IP
  application/account-management/Api/Program.cs
  application/account-management/Workers/Program.cs
  application/back-office/Api/Program.cs
  application/back-office/Workers/Program.cs
  application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
Labels: enhancement
