Repository platformplatform/PlatformPlatform, pull requests merged in 2024-05, with the labels that each got.

#446 Update WSL guide installing and trusting certificates
  README.md
Labels: enhancement

#445 Revert React and React Dom to canary
  application/account-management/WebApp/package.json
Labels: bug

#452 Update to .NET Aspire preview 7
  application/AppHost/Program.cs
  application/Directory.Packages.props
  developer-cli/Installation/PrerequisitesChecker.cs
Labels: enhancement

#453 Use rimraf for operating system agnostic deleting WebApp dist folder
  application/account-management/WebApp/package.json
Labels: bug

#454 Update rimraf usage to only delete contents inside the dist folder, keeping the folder itself
  application/account-management/WebApp/package.json
Labels: bug

#455 Enhance the CLI for setting up CI/CD and improve the first-time start of Aspire AppHost for better stability and usability
  .github/workflows/application.yml
  README.md
  developer-cli/Commands/BuildCommand.cs
  developer-cli/Commands/CodeCleanupCommand.cs
  developer-cli/Commands/CodeCoverageCommand.cs
  developer-cli/Commands/CodeInspectionsCommand.cs
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
  developer-cli/Commands/DevCommand.cs
  developer-cli/Commands/InstallCommand.cs
  developer-cli/Commands/TestCommand.cs
  developer-cli/Commands/TranslateCommand.cs
  developer-cli/Installation/Configuration.cs
  developer-cli/Installation/PrerequisitesChecker.cs
  developer-cli/Utilities/ProcessHelper.cs
Labels: enhancement

#457 Prepare PlatformPlatform solutions for multiple self-contained systems
  .github/workflows/application.yml
  .gitignore
  application/AccountManagement.slnf
  application/AppGateway/AppGateway.csproj
  application/AppGateway/appsettings.json
  application/AppHost/AppHost.csproj
  application/AppHost/Program.cs
  application/PlatformPlatform.sln
  application/SharedKernel.slnf
  application/account-management/AccountManagement.sln
  application/account-management/Api/AccountManagement.Api.csproj
  application/account-management/Api/AccountRegistrations/AccountRegistrationsEndpoints.cs
  application/account-management/Api/Tenants/TenantEndpoints.cs
  application/account-management/Api/Users/UserEndpoints.cs
  application/account-management/Application/AccountManagement.Application.csproj
  application/account-management/Domain/AccountManagement.Domain.csproj
  application/account-management/Infrastructure/AccountManagement.Infrastructure.csproj
  application/account-management/Tests/AccountManagement.Tests.csproj
  application/account-management/Tests/Api/AccountRegistrations/AccountRegistrationsTests.cs
  application/account-management/Tests/Api/Tenants/TenantEndpointsTests.cs
  application/account-management/Tests/Api/Users/UserEndpointsTests.cs
  application/account-management/WebApp/AccountManagement.WebApp.esproj
  application/account-management/WebApp/app/register/components/actions.ts
  application/account-management/WebApp/dist/index.html
  application/account-management/WebApp/eslint.config.js
  application/account-management/WebApp/main.tsx
  application/account-management/WebApp/package.json
  application/account-management/WebApp/public/index.html
  application/account-management/WebApp/rspack.config.ts
  application/account-management/Workers/AccountManagement.Workers.csproj
  application/client-foundation/clientFilesystemRouter/lib/ClientFilesystemRouter.ts
  application/client-foundation/clientFilesystemRouter/lib/generateReactRouter.ts
  application/shared-kernel/ApiCore/SharedKernel.ApiCore.csproj
  application/shared-kernel/ApplicationCore/SharedKernel.ApplicationCore.csproj
  application/shared-kernel/DomainCore/SharedKernel.DomainCore.csproj
  application/shared-kernel/InfrastructureCore/SharedKernel.InfrastructureCore.csproj
  application/shared-kernel/SharedKernel.sln
  application/shared-kernel/Tests/SharedKernel.Tests.csproj
  developer-cli/Commands/BuildCommand.cs
  developer-cli/Commands/CodeCleanupCommand.cs
  developer-cli/Commands/CodeCoverageCommand.cs
  developer-cli/Commands/CodeInspectionsCommand.cs
  developer-cli/Commands/TestCommand.cs
  developer-cli/Utilities/SolutionHelper.cs
Labels: documentation

#458 Split application.yml for isolated deployment of AppGateway and AccountManagement
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
  README.md
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Labels: enhancement

#459 Create Azure infrastructure for Back Office self-contained system
  cloud-infrastructure/cluster/deploy-cluster.sh
  cloud-infrastructure/cluster/main-cluster.bicep
Labels: enhancement

#460 Change Account Management build to use AccountManagement.slnf
  .github/workflows/account-management.yml
  application/SharedKernel.slnf
  application/account-management/AccountManagement.slnf
Labels: enhancement

#461 Stabilize infrastructure deployments by fixing race conditions and making deployment names unique
  cloud-infrastructure/cluster/deploy-cluster.sh
  cloud-infrastructure/cluster/main-cluster.bicep
  cloud-infrastructure/environment/deploy-environment.sh
  cloud-infrastructure/environment/main-environment.bicep
  cloud-infrastructure/modules/application-insights.bicep
  cloud-infrastructure/modules/container-app.bicep
  cloud-infrastructure/modules/microsoft-sql-server-diagnostic.bicep
  cloud-infrastructure/modules/storage-account.bicep
  cloud-infrastructure/modules/user-assigned-managed-identity.bicep
  cloud-infrastructure/shared/deploy-shared.sh
  cloud-infrastructure/shared/main-shared.bicep
Labels: enhancement

#462 Suppress TypeScript errors in generated client router
  .gitignore
  application/client-foundation/clientFilesystemRouter/lib/pageReactRoutesCode.ts
Labels: enhancement

#463 Streamline workflows and build processes
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
Labels: enhancement

#464 Revert changes to GitHub Actions workflow for artifact publishing
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
Labels: bug

#466 Install NodeJS and node modules for multiple self-contained systems
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
Labels: enhancement

#469 Rename azure resources and restructure GitHub workflows
  .github/workflows/_deploy-container.yml
  .github/workflows/_publish-container.yml
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
  .github/workflows/back-office.yml
  .github/workflows/cloud-infrastructure.yml
  README.md
  cloud-infrastructure/README.md
  cloud-infrastructure/cluster/config/development-west-europe.sh
  cloud-infrastructure/cluster/config/production-west-europe.sh
  cloud-infrastructure/cluster/config/staging-west-europe.sh
  cloud-infrastructure/cluster/deploy-cluster.sh
  cloud-infrastructure/cluster/grant-database-permissions.sh
  cloud-infrastructure/cluster/main-cluster.bicep
  cloud-infrastructure/environment/config/development.sh
  cloud-infrastructure/environment/config/production.sh
  cloud-infrastructure/environment/config/staging.sh
  cloud-infrastructure/environment/deploy-environment.sh
  cloud-infrastructure/environment/main-environment.bicep
  cloud-infrastructure/modules/application-insights.bicep
  cloud-infrastructure/modules/microsoft-sql-server-diagnostic.bicep
  cloud-infrastructure/modules/microsoft-sql-server-elastic-pool.bicep
  cloud-infrastructure/modules/private-dns-zones.bicep
  cloud-infrastructure/modules/private-endpoint-sql-server.bicep
  cloud-infrastructure/modules/resource-group-lock.bicep
  cloud-infrastructure/modules/service-bus.bicep
  cloud-infrastructure/modules/storage-account.bicep
  cloud-infrastructure/modules/user-assigned-managed-identity.bicep
  cloud-infrastructure/shared/config/shared-development.sh
  cloud-infrastructure/shared/config/shared.sh
  cloud-infrastructure/shared/deploy-shared.sh
  cloud-infrastructure/shared/main-shared.bicep
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
  developer-cli/Utilities/SolutionHelper.cs
Labels: enhancement

#473 Update .NET Aspire to GA and update other NuGet packages to latest versions
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
  .github/workflows/back-office.yml
  application/Directory.Packages.props
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
  developer-cli/Installation/PrerequisitesChecker.cs
Labels: enhancement

#474 Update SQL Server Admin AD group naming and adjust permissions
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Labels: enhancement

#475 Update CI/CD steps and configure-continuous-deployments CLI command
  .github/workflows/cloud-infrastructure.yml
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Labels: bug

#476 Make Azure location configurable
  .github/workflows/_deploy-container.yml
  .github/workflows/_deploy-infrastructure.yml
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
  .github/workflows/back-office.yml
  .github/workflows/cloud-infrastructure.yml
  cloud-infrastructure/cluster/config/development-west-europe.sh
  cloud-infrastructure/cluster/config/production-west-europe.sh
  cloud-infrastructure/cluster/config/staging-west-europe.sh
  cloud-infrastructure/cluster/deploy-cluster.sh
  cloud-infrastructure/cluster/firewall.sh
  cloud-infrastructure/cluster/grant-database-permissions.sh
  cloud-infrastructure/environment/config/development.sh
  cloud-infrastructure/environment/config/production.sh
  cloud-infrastructure/environment/config/staging.sh
  cloud-infrastructure/environment/deploy-environment.sh
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Labels: enhancement

#477 Improve database migration and container apps logging
  application/account-management/Workers/Program.cs
  application/back-office/Workers/Program.cs
  cloud-infrastructure/cluster/deploy-cluster.sh
  cloud-infrastructure/cluster/main-cluster.bicep
  cloud-infrastructure/modules/container-apps-environment.bicep
  cloud-infrastructure/modules/microsoft-sql-database.bicep
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
Labels: enhancement
