Repository platformplatform/PlatformPlatform, pull requests merged in 2024-07, with the labels that each got.

#521 Configure HTTPS health probes and secure internal health endpoints
  application/AppGateway/Program.cs
  application/AppGateway/Transformations/BlockInternalApiTransform.cs
  application/AppGateway/Transformations/ManagedIdentityTransform.cs
  application/AppGateway/appsettings.json
  application/shared-kernel/ApiCore/Endpoints/HealthEndpoints.cs
  cloud-infrastructure/cluster/main-cluster.bicep
  cloud-infrastructure/modules/container-app.bicep
Labels: enhancement

#527 Ensure GitHub workflows are enabled when running configure-continuous-deployments CLI command
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
  developer-cli/Utilities/ProcessHelper.cs
Labels: enhancement

#528 Upgrade dependencies and bump CLI prerequisite checks
  application/Directory.Packages.props
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
  application/back-office/WebApp/shared/lib/api/BackOffice.Api.json
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
  developer-cli/Commands/TranslateCommand.cs
  developer-cli/DeveloperCli.csproj
  developer-cli/Installation/PrerequisitesChecker.cs
Labels: enhancement

#523 Fix white screen issue when loading website and improve build performance of frontend
  application/account-management/WebApp/package.json
  application/account-management/WebApp/pages/-landing/sections/CtaSection2.tsx
  application/account-management/WebApp/pages/-landing/sections/FeatureSection.tsx
  application/account-management/WebApp/pages/-landing/sections/FeatureSection3.tsx
  application/account-management/WebApp/pages/-landing/sections/FooterSection.tsx
  application/account-management/WebApp/pages/-landing/sections/TechnologySection.tsx
  application/account-management/WebApp/pages/-landing/sections/TechnologySection2.tsx
  application/back-office/WebApp/package.json
  application/package-lock.json
  application/package.json
  application/shared-kernel/ApiCore/SinglePageApp/SinglePageAppConfiguration.cs
  application/shared-webapp/build/package.json
  application/shared-webapp/infrastructure/package.json
  application/shared-webapp/ui/package.json
  application/shared-webapp/utils/package.json
  application/turbo.json
Labels: enhancement

#529 Change liveness and readiness health probes scheme from HTTPS to HTTP
  cloud-infrastructure/modules/container-app.bicep
Labels: bug

#531 Enhance deployment workflows with monitoring and update health probes for workers
  .github/workflows/_deploy-container.yml
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
  .github/workflows/back-office.yml
  cloud-infrastructure/cluster/main-cluster.bicep
Labels: enhancement

#532 Ensure Aspire is using the the latest version of the Azurite image
  application/AppHost/Program.cs
Labels: enhancement

#542 Design review of components and design tokens
  application/account-management/WebApp/pages/admin/users/-components/UserTable.tsx
  application/shared-webapp/ui/components/Badge.tsx
  application/shared-webapp/ui/components/Popover.tsx
  application/shared-webapp/ui/components/SideMenu.tsx
  application/shared-webapp/ui/components/Table.tsx
  application/shared-webapp/ui/copyImages.js
  application/shared-webapp/ui/images/logo-mark.svg
  application/shared-webapp/ui/images/logo-wrap.svg
  application/shared-webapp/ui/images/powered-by.svg
  application/shared-webapp/ui/package.json
Labels: enhancement

#541 Update login/register pages, and enhance admin features
  application/account-management/Application/Users/GetUsers.cs
  application/account-management/Application/Users/GetUsersResponseDto.cs
  application/account-management/WebApp/pages/-landing/sections/FeatureSection3.tsx
  application/account-management/WebApp/pages/-landing/sections/HeroSection.tsx
  application/account-management/WebApp/pages/__root.tsx
  application/account-management/WebApp/pages/admin/index.tsx
  application/account-management/WebApp/pages/admin/users/-components/UserModals/AccountModal.tsx
  application/account-management/WebApp/pages/admin/users/-components/UserModals/DeleteAccountModal.tsx
  application/account-management/WebApp/pages/admin/users/-components/UserModals/UserProfileModal.tsx
  application/account-management/WebApp/pages/admin/users/-components/UserTable.tsx
  application/account-management/WebApp/pages/admin/users/-components/UserTabs.tsx
  application/account-management/WebApp/pages/admin/users/index.tsx
  application/account-management/WebApp/pages/login/-components/LoginForm.tsx
  application/account-management/WebApp/pages/login/index.tsx
  application/account-management/WebApp/pages/register/-components/CompleteAccountRegistrationForm.tsx
  application/account-management/WebApp/pages/register/-components/StartAccountRegistrationForm.tsx
  application/account-management/WebApp/pages/register/index.tsx
  application/account-management/WebApp/pages/register/verify/index.tsx
  application/account-management/WebApp/public/apple-touch-icon.png
  application/account-management/WebApp/public/favicon.ico
  application/account-management/WebApp/public/index.html
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
  application/account-management/WebApp/shared/translations/locale/da-DK.po
  application/account-management/WebApp/shared/translations/locale/en-US.po
  application/account-management/WebApp/shared/translations/locale/pseudo.po
  application/account-management/WebApp/shared/ui/LocaleSwitcher.tsx
  application/account-management/WebApp/shared/ui/images/logo-mark.png
  application/account-management/WebApp/shared/ui/images/powered-by.png
  application/account-management/WebApp/shared/ui/oneTimePassword/Digit.tsx
  application/back-office/WebApp/pages/__root.tsx
  application/back-office/WebApp/public/index.html
  application/shared-webapp/build/plugin/DevelopmentServerPlugin.ts
  application/shared-webapp/infrastructure/auth/AuthenticationProvider.tsx
  application/shared-webapp/infrastructure/auth/hooks.ts
  application/shared-webapp/ui/components/Pagination.tsx
  application/shared-webapp/ui/components/SideMenu.tsx
  application/shared-webapp/utils/string/getCamelCase.ts
  application/shared-webapp/utils/string/getPascalCase.ts
Labels: enhancement

#550 Design review user management and mobile
  application/account-management/WebApp/routes/(index)/-components/FeatureSection3.tsx
  application/account-management/WebApp/routes/(index)/-components/HeroSection.tsx
  application/account-management/WebApp/routes/__root.tsx
  application/account-management/WebApp/routes/admin/index.tsx
  application/account-management/WebApp/routes/admin/users/-components/UserInvite.tsx
  application/account-management/WebApp/routes/admin/users/-components/UserQuerying.tsx
  application/account-management/WebApp/routes/admin/users/-components/UserTable.tsx
  application/account-management/WebApp/routes/admin/users/index.tsx
  application/account-management/WebApp/shared/components/SharedSideMenu.tsx
  application/account-management/WebApp/shared/components/topMenu/AvatarButton.tsx
  application/account-management/WebApp/shared/components/topMenu/index.tsx
  application/back-office/WebApp/routes/__root.tsx
  application/package-lock.json
  application/package.json
  application/shared-webapp/infrastructure/themeMode/ThemeModeSelector.tsx
  application/shared-webapp/infrastructure/themeMode/useThemeMode.tsx
  application/shared-webapp/infrastructure/translations/LocaleSwitcher.tsx
  application/shared-webapp/ui/components/Breadcrumbs.tsx
  application/shared-webapp/ui/components/Button.tsx
  application/shared-webapp/ui/components/Calendar.tsx
  application/shared-webapp/ui/components/Checkbox.tsx
  application/shared-webapp/ui/components/ComboBox.tsx
  application/shared-webapp/ui/components/DatePicker.tsx
  application/shared-webapp/ui/components/DateRangePicker.tsx
  application/shared-webapp/ui/components/Input.tsx
  application/shared-webapp/ui/components/Menu.tsx
  application/shared-webapp/ui/components/Modal.tsx
  application/shared-webapp/ui/components/Pagination.tsx
  application/shared-webapp/ui/components/SearchField.tsx
  application/shared-webapp/ui/components/SideMenu.tsx
  application/shared-webapp/ui/components/Table.tsx
  application/shared-webapp/ui/components/Tabs.tsx
  application/shared-webapp/ui/tailwind-preset.ts
  application/shared-webapp/ui/tailwind.css
  application/shared-webapp/ui/theme/ThemeModeSelector.tsx
  application/shared-webapp/ui/theme/mode/ThemeMode.tsx
  application/shared-webapp/ui/theme/mode/useStorageThemeMode.ts
  application/shared-webapp/ui/theme/mode/useSystemThemeMode.ts
  application/shared-webapp/ui/theme/mode/utils.ts
Labels: enhancement, TypeScript

#558 Improve the ergonomics of data loading in the front-end
  application/account-management/WebApp/package.json
  application/account-management/WebApp/routes/admin/index.tsx
  application/account-management/WebApp/routes/admin/users/-components/UserTable.tsx
  application/account-management/WebApp/routes/admin/users/-components/UserTabs.tsx
  application/account-management/WebApp/routes/admin/users/index.tsx
  application/account-management/WebApp/routes/register/-shared/actions.ts
  application/account-management/WebApp/routes/register/-shared/hooks.tsx
  application/account-management/WebApp/routes/register/-shared/registrationState.ts
  application/account-management/WebApp/routes/register/expired.tsx
  application/account-management/WebApp/routes/register/index.tsx
  application/account-management/WebApp/routes/register/verify.tsx
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
  application/account-management/WebApp/shared/lib/api/client.ts
  application/account-management/WebApp/shared/translations/locale/da-DK.po
  application/account-management/WebApp/shared/translations/locale/en-US.po
  application/back-office/WebApp/package.json
  application/back-office/WebApp/shared/lib/api/client.ts
  application/package-lock.json
  application/package.json
  application/shared-kernel/ApiCore/ApiCoreConfiguration.cs
  application/shared-kernel/ApiCore/SchemaProcessor/StronglyTypedDocumentProcessor.cs
  application/shared-webapp/build/environment.d.ts
  application/shared-webapp/build/plugin/RunTimeEnvironmentPlugin.ts
  application/shared-webapp/infrastructure/api/ApiReactHook.ts
  application/shared-webapp/infrastructure/api/CachedClientMethod.ts
  application/shared-webapp/infrastructure/api/ClientMethodWithProblemDetails.ts
  application/shared-webapp/infrastructure/api/ErrorList.ts
  application/shared-webapp/infrastructure/api/HandleFluentValidationErrors.ts
  application/shared-webapp/infrastructure/api/PlatformApiClient.ts
  application/shared-webapp/infrastructure/api/PlatformServerAction.ts
  application/shared-webapp/infrastructure/api/ProblemDetails.ts
  application/shared-webapp/infrastructure/auth/actions.ts
  application/shared-webapp/infrastructure/auth/mock.api.ts
  application/shared-webapp/ui/components/FormErrorMessage.tsx
  application/shared-webapp/utils/hooks/useMemorizedObject.ts
  application/shared-webapp/utils/object/isKeyof.ts
Labels: enhancement, .NET, TypeScript
