Repository platformplatform/PlatformPlatform, pull requests merged in 2025-01, with the labels that each got.

#656 Add rules for AI editors to ensure consistency with project guidelines
  .cursorrules
  .github/copilot-instructions.md
  .gitignore
  application/.cursorrules
Labels: Enhancement

#663 Add GitHub Action to enforce Git conventions
  .github/workflows/validate-pull-request-conventions.yml
Labels: Enhancement

#664 Fix Git convention validation for forked repositories and enhance rules
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/validate-pull-request-conventions.yml
Labels: Enhancement

#665 Improve Developer CLI error handling for prerequisites and Azure subscription validation
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
  developer-cli/Installation/Prerequisite.cs
Labels: Bug

#666 Resending the one time password for login and signup does
  application/account-management/Api/Endpoints/AuthenticationEndpoints.cs
  application/account-management/Api/Endpoints/SignupEndpoints.cs
  application/account-management/Core/Features/Authentication/Commands/ResendLoginCode.cs
  application/account-management/Core/Features/Authentication/Domain/Login.cs
  application/account-management/Core/Features/Signups/Commands/ResendSignupCode.cs
  application/account-management/Core/Features/Signups/Commands/StartSignup.cs
  application/account-management/Core/Features/Signups/Domain/Signup.cs
  application/account-management/Core/Features/TelemetryEvents.cs
  application/account-management/Tests/Signups/StartSignupTests.cs
  application/account-management/WebApp/routes/login/verify.tsx
  application/account-management/WebApp/routes/signup/index.tsx
  application/account-management/WebApp/routes/signup/verify.tsx
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
Labels: Enhancement

#662 Allow serving local environment from any address
  application/AppHost/ConfigurationExtensions.cs
  application/AppHost/Program.cs
  application/account-management/Api/Properties/launchSettings.json
  application/back-office/Api/Properties/launchSettings.json
  application/shared-kernel/SharedKernel/SinglePageApp/SinglePageAppConfiguration.cs
Labels: Enhancement

#668 Allow multiple sentences in commit messages for PlatformPlatform cherry-picked commits
  .github/workflows/validate-pull-request-conventions.yml
Labels: Enhancement

#669 Add user summary metrics to Admin Dashboard
  application/account-management/Api/Endpoints/UserEndpoints.cs
  application/account-management/Core/Features/Signups/Queries/IsSubdomainFree.cs
  application/account-management/Core/Features/Tenants/Queries/GetTenant.cs
  application/account-management/Core/Features/Users/Domain/UserRepository.cs
  application/account-management/Core/Features/Users/Queries/GetUser.cs
  application/account-management/Core/Features/Users/Queries/GetUserSummary.cs
  application/account-management/WebApp/routes/admin/index.tsx
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
  application/account-management/WebApp/shared/translations/locale/da-DK.po
  application/account-management/WebApp/shared/translations/locale/en-US.po
  application/account-management/WebApp/shared/translations/locale/nl-NL.po
  application/shared-webapp/infrastructure/auth/constants.ts
Labels: Enhancement

#670 Upgrade GitHub runners to Ubuntu 24.04 and improve Bicep output parsing
  .github/workflows/_deploy-container.yml
  .github/workflows/_deploy-infrastructure.yml
  .github/workflows/account-management.yml
  .github/workflows/app-gateway.yml
  .github/workflows/back-office.yml
  .github/workflows/validate-pull-request-conventions.yml
  cloud-infrastructure/cluster/deploy-cluster.sh
  cloud-infrastructure/cluster/main-cluster.bicep
  cloud-infrastructure/environment/deploy-environment.sh
Labels: Enhancement

#671 Update AI Editor rules files with detailed PlatformPlatform conventions
  .github/copilot-instructions.md
Labels: Enhancement

#672 Redirect users to the intended page after successful login
  application/account-management/WebApp/routes/login/index.tsx
  application/account-management/WebApp/routes/login/verify.tsx
Labels: Enhancement

#673 Persist side menu state in the admin center
  application/shared-webapp/ui/components/SideMenu.tsx
  application/shared-webapp/ui/hooks/useLocalStorage.ts
Labels: Enhancement

#674 Enable seamless updates to user data and locale without full page reloads
  .github/copilot-instructions.md
  application/AppGateway/Middleware/AuthenticationCookieMiddleware.cs
  application/account-management/Api/Endpoints/AuthenticationEndpoints.cs
  application/account-management/Api/Endpoints/UserEndpoints.cs
  application/account-management/Core/Features/Users/Commands/UpdateUser.cs
  application/account-management/Tests/Users/UpdateUserTests.cs
  application/account-management/WebApp/routes/admin/users/-components/InviteUserModal.tsx
  application/account-management/WebApp/shared/components/AvatarButton.tsx
  application/account-management/WebApp/shared/components/userModals/UserProfileModal.tsx
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
  application/shared-kernel/SharedKernel/ApiResults/ApiResult.cs
  application/shared-kernel/SharedKernel/ApiResults/ApiResultExtensions.cs
  application/shared-kernel/SharedKernel/Authentication/AuthenticationTokenHttpKeys.cs
  application/shared-webapp/infrastructure/translations/LocaleSwitcher.tsx
Labels: Enhancement

#675 Remember to use language choice between browser sessions
  application/account-management/Core/Features/Signups/Commands/CompleteSignup.cs
  application/account-management/Core/Features/Tenants/Commands/CreateTenant.cs
  application/account-management/Core/Features/Users/Commands/CreateUser.cs
  application/account-management/Core/Features/Users/Commands/InviteUser.cs
  application/account-management/Core/Features/Users/Domain/User.cs
  application/account-management/Tests/DatabaseSeeder.cs
  application/account-management/Tests/Users/CreateUserTests.cs
  application/account-management/WebApp/routes/__root.tsx
  application/account-management/WebApp/routes/signup/verify.tsx
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
  application/back-office/WebApp/routes/__root.tsx
  application/shared-webapp/infrastructure/translations/LocaleSwitcher.tsx
  application/shared-webapp/infrastructure/translations/constants.ts
  application/shared-webapp/infrastructure/translations/useInitializeLocale.ts
Labels: Enhancement

#676 Simplify DbContext by extracting aggregate configuration into dedicated classes
  application/Directory.Packages.props
  application/account-management/Core/Database/AccountManagementDbContext.cs
  application/account-management/Core/Features/Authentication/Domain/LoginConfiguration.cs
  application/account-management/Core/Features/Signups/Domain/SignupConfiguration.cs
  application/account-management/Core/Features/Signups/Domain/SignupRepository.cs
  application/account-management/Core/Features/Tenants/Domain/TenantConfiguration.cs
  application/account-management/Core/Features/Users/Domain/UserConfiguration.cs
  application/account-management/Tests/DatabaseSeeder.cs
  application/shared-kernel/SharedKernel/EntityFramework/ModelBuilderExtensions.cs
  application/shared-kernel/SharedKernel/EntityFramework/SharedKernelDbContext.cs
  application/shared-kernel/SharedKernel/SharedKernel.csproj
Labels: Enhancement

#678 Fix logout issue on pages without user context
  application/account-management/WebApp/shared/components/AvatarButton.tsx
Labels: Enhancement

#679 Fix JetBrains warnings and update ReSharper version to 2024.3.4
  application/dotnet-tools.json
  application/shared-kernel/Tests/Behaviors/PublishDomainEventsPipelineBehaviorTests.cs
  application/shared-kernel/Tests/Behaviors/UnitOfWorkPipelineBehaviorTests.cs
  application/shared-kernel/Tests/Persistence/RepositoryTests.cs
Labels: Enhancement

#680 Upgrade NuGet packages with exceptions for FluentValidation
  application/AppGateway/Program.cs
  application/Directory.Packages.props
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
  application/back-office/WebApp/shared/lib/api/BackOffice.Api.json
Labels: Enhancement

#682 Move logged-in user endpoints to /users/me and apply code cleanup
  application/account-management/Api/Endpoints/UserEndpoints.cs
  application/account-management/Core/Features/Authentication/Commands/CompleteLogin.cs
  application/account-management/Core/Features/Authentication/Commands/ResendLoginCode.cs
  application/account-management/Core/Features/Signups/Commands/CompleteSignup.cs
  application/account-management/Core/Features/Signups/Commands/ResendSignupCode.cs
  application/account-management/Core/Features/Users/Commands/ChangeLocale.cs
  application/account-management/Core/Features/Users/Commands/ChangeUserRole.cs
  application/account-management/Core/Features/Users/Commands/DeleteUser.cs
  application/account-management/Core/Features/Users/Commands/RemoveAvatar.cs
  application/account-management/Core/Features/Users/Commands/UpdateAvatar.cs
  application/account-management/Core/Features/Users/Commands/UpdateCurrentUser.cs
  application/account-management/Core/Features/Users/Domain/UserRepository.cs
  application/account-management/Core/Features/Users/Queries/GetCurrentUser.cs
  application/account-management/Tests/Users/GetCurrentUserTests.cs
  application/account-management/Tests/Users/UpdateCurrentUserTests.cs
  application/account-management/WebApp/routes/(index)/-components/FeatureSection4.tsx
  application/account-management/WebApp/shared/components/userModals/UserProfileModal.tsx
  application/account-management/WebApp/shared/lib/api/AccountManagement.Api.json
  application/shared-kernel/SharedKernel/Configuration/SharedDependencyConfiguration.cs
  application/shared-kernel/SharedKernel/DomainEvents/IDomainEvent.cs
Labels: Enhancement

#683 Add Developer CLI command to easily amend commits with co-authors
  developer-cli/Commands/AmendAsCoAuthorCommand.cs
Labels: Enhancement

#684 Fix bug in configure-continuous-deployments command and maintain developer CLI
  developer-cli/Commands/CodeCoverageCommand.cs
  developer-cli/Commands/ConfigureContinuousDeploymentsCommand.cs
  developer-cli/Commands/InstallCommand.cs
  developer-cli/Commands/PullPlatformPlatformChangesCommand.cs
  developer-cli/Commands/UninstallCommand.cs
  developer-cli/DeveloperCli.csproj
  developer-cli/Installation/Configuration.cs
  developer-cli/Utilities/GitHelper.cs
  developer-cli/Utilities/ProcessHelper.cs
  developer-cli/dotnet-tools.json
  developer-cli/global.json
Labels: Bug, Enhancement

#685 Restore .NET global.json in application folder and upgrade to .NET 9.0.102
  application/global.json
Labels: Bug

#686 Fix translation updates and improve LocaleSwitcher usability
  application/account-management/WebApp/shared/components/topMenu/index.tsx
  application/back-office/WebApp/shared/components/topMenu/index.tsx
  application/shared-webapp/infrastructure/translations/LocaleSwitcher.tsx
  application/shared-webapp/infrastructure/translations/Translation.tsx
Labels: Enhancement
